"use client"

import { useState } from "react";

export const metadata= {
  title: 'Counter',
  description: 'Generated by Next.js',
}

export default function CounterPage(){
    const [count, setCount] = useState(0);

    return(
        <>
        <p>Count: {count}</p>
        <button onClick={()=>setCount(count + 1)}>Increment</button>
        </>
    )
}
