import CounterPage from "./Counter";
import { Metadata } from "next";

export const metadata : Metadata = {
  title: {
    absolute: "Blog"
  },
  description: "Generated by Next.js",
};

// ✅ No "use client" here — this is a server component that renders a client child
export default function CounterRoute() {
  return (
    <>
      <CounterPage />
    </>
  );
}
