// app/layout.tsx

import type { Metadata } from 'next'
import Header from './Header'
import Footer from './Footer'
import { ErrorWrapper } from './error-wrapper'

export const metadata: Metadata = {
  title: {
    default: "Next.js tutorial",//Acts as a fallback for any unspecified title
    template: "%s | codevolution",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,//where the page content will go
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Header />
       <ErrorWrapper>
        {children}
</ErrorWrapper>
    <Footer />
      </body>
    </html>
  )
}


/*Metadata rules
1. Both layout.tsx and page.tsx can export metadata. Layout metadata applies to all
its pages, while page metadata is specific to that page.
2. Metadata follows a top-down order, starting from the root level.
*/